title: Interaktív tanítás
description: Matematikaoktatás felfedeztetően
author: HUN-REN Rényi Alfréd Matematikai Kutatóintézet Szakmódszertani Osztálya
logo: /images/logo-it.png

plugins:
  - jekyll-remote-theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

# Oldalstruktúra
show_sidebar: true
show_dark_toggle: false     # nem jelenik meg a világos/sötét mód kapcsoló
show_posts: false           # nem listázza a blogposztokat
show_footer: false          # alul semmi extra
show_github: false          # alul semmi extra

toc_label: "Információk"

navigation:
  - name: Felhívás
    link: ./
    sublist:
      - name: Részletek
        link: ./about.html
      - name: Jelentkezés
        link: https://forms.gle/JC12DRATg5buoCRL6
